#!/bin/bash

OUTDIR=out
DEFAULT_TARGET=build
BASE_DIR=$(dirname $0)

function main {
	if [ "$1" == "" ]; then
		TARGET=$DEFAULT_TARGET
	else
		TARGET=$1
	fi
	
	$TARGET
}

function build {
	echo "[*] Building debugr"
	mkdir -p $OUTDIR
	cd $OUTDIR
	cmake -B . -S .. && make && cd ..
}

function clean {
	echo "[*] Cleaning environment"
	rm -rf $OUTDIR
}

cd $BASE_DIR
main $*
